language: php

php:
  - 5.6

sudo: false

env:
    - LARAVEL_VERSION="5.2.*"


before_script:
  - /home/travis/.phpenv/versions/5.6/bin/composer self-update
  - composer self-update
  - cp .env.travis .env
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
  - mysql -e 'create database IF NOT EXISTS  cineacademy;'   -uroot
  - mysql -uroot cineacademy < mysql/cineacademy.sql
  - php artisan  db:seed

script: phpunit

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    - julien@meetserious.com


services:
  - redis-server
  - elasticsearch
  - mongodb
  - mysql
