language: php

php:
  - 5.6

sudo: false

env:
    - LARAVEL_VERSION="5.1.*"

before_install:
  - if [ "$MONGO_VERSION" != "" ]; then pecl -q install -f mongo-2.4.9; fi # Use a specific driver version when needed rather than the one shipped by Travis
  - echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - echo "extension=redis.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`


before_script:
  - /home/travis/.phpenv/versions/5.6/bin/composer self-update
  - composer self-update
  - cp .env.travis .env
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
  - mysql -e 'create database IF NOT EXISTS  cineacademy;'   -uroot
  - mysql -uroot cineacademy < mysql/cineacademy.sql
  - php artisan  db:seed

script: phpunit

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    - julien@meetserious.com


services:
  - redis-server
  - elasticsearch
  - mongodb
  - mysql
